<script>

var totalToAddUsers = 0;

function addAnother()
{
	totalToAddUsers++;
	document.getElementById("totalAdd").value = totalToAddUsers;
	var toAdd = "<table class=\"news_item_table\" width=\"100%\">\
	<tr>\
    <td width=\"33%\">\
    Student:\
    </td>\
    <td width=\"67%\">\
    " + totalToAddUsers + "\
    </td>\
    </tr>\
    <tr>\
    <td colspan=\"2\">\
    &nbsp;\
    </td>\
    </tr>\
	<tr>\
    <td width=\"33%\">\
    Email Address:\
    </td>\
    <td width=\"67%\">\
    <input type=\"text\" name=\"email_" + totalToAddUsers + "\" value=\"\" style=\"width:90%\"></input>\
    </td>\
    </tr>\
    <tr>\
    <td width=\"33%\">\
    First Name:\
    </td>\
    <td width=\"67%\">\
    <input type=\"text\" name=\"fname_" + totalToAddUsers + "\" value=\"\" style=\"width:90%\"></input>\
    </td>\
    </tr>\
    <tr>\
    <td width=\"33%\">\
    Middle Name:\
    </td>\
    <td width=\"67%\">\
    <input type=\"text\" name=\"mname_" + totalToAddUsers + "\" value=\"\" style=\"width:90%\"></input>\
    </td>\
    </tr>\
    <tr>\
    <td width=\"33%\">\
    Last Name:\
    </td>\
    <td width=\"67%\">\
    <input type=\"text\" name=\"lname_" + totalToAddUsers + "\" value=\"\" style=\"width:90%\"></input>\
    </td>\
    </tr>\
    <tr>\
    <td width=\"33%\">\
    Password:\
    </td>\
    <td width=\"67%\">\
    <input type=\"text\" name=\"password_" + totalToAddUsers + "\" value=\"Do not change for an autogenerated value.\" style=\"width:90%\"></input>\
    </td>\
    </tr>\
    <tr>\
    <td width=\"33%\">\
    Password:\
    </td>\
    <td width=\"67%\">\
    <input type=\"text\" name=\"course_" + totalToAddUsers + "\" value=\"\" style=\"width:90%\"></input>\
    </td>\
    </tr>\
    </table>";
	document.getElementById("add_user_table").innerHTML += toAdd;
}

</script>