<script>

var totalToAddUsers = 0;

function addAnother()
{
	totalToAddUsers++;
	document.getElementById("totalAdd").value = totalToAddUsers;
	var toAdd = "<table class=\"news_item_table\" width=\"100%\">\
	<tr>\
    <td>\
    Student:\
    </td>\
    <td width=\"100%\">\
    <div align=\"right\">\
    " + totalToAddUsers + "\
    </div>\
    </td>\
    </tr>\
    <tr>\
    <td colspan=\"2\">\
    &nbsp;\
    </td>\
    </tr>\
	<tr>\
    <td width=\"100%\">\
    <input type=\"text\" name=\"email_" + totalToAddUsers + "\" value=\"Email\" onChange=\"this.setAttribute('value', this.value);\" onfocus=\"clearText(this);\" style=\"width:100%\"></input>\
    </td>\
    </tr>\
    <tr>\
    <td width=\"100%\">\
    <input type=\"text\" name=\"fname_" + totalToAddUsers + "\" onChange=\"this.setAttribute('value', this.value);\" onfocus=\"clearText(this);\" value=\"First Name\" style=\"width:100%\"></input>\
    </td>\
    </tr>\
    <tr style=\"display:none;\">\
    <td width=\"33%\">\
    Middle Name:\
    </td>\
    <td width=\"67%\">\
    <input type=\"text\" name=\"mname_" + totalToAddUsers + "\" value=\"\" style=\"width:90%\"></input>\
    </td>\
    </tr>\
    <tr>\
    <td width=\"67%\">\
    <input type=\"text\" name=\"lname_" + totalToAddUsers + "\" onChange=\"this.setAttribute('value', this.value);\" onfocus=\"clearText(this);\" value=\"Last Name\" style=\"width:100%\"></input>\
    </td>\
    </tr>\
    <tr>\
    <td width=\"100%\">\
    <input type=\"text\" name=\"password_" + totalToAddUsers + "\" onChange=\"this.setAttribute('value', this.value);\" value=\"Password: Do not change for an autogenerated value.\" style=\"width:100%\"></input>\
    </td>\
    </tr>\
    <tr>\
    <td width=\"100%\">\
    <input type=\"text\" name=\"course_" + totalToAddUsers + "\" onChange=\"this.setAttribute('value', this.value);\" onfocus=\"clearText(this);\" value=\"Course\" style=\"width:100%\"></input>\
    </td>\
    </tr>\
    </table>";
	document.getElementById("add_user_table").innerHTML += toAdd;
}

</script>