<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<%@include file="./WEB-INF/includes/includes.jsp" %>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>RevEngE</title>

</head>

<body>
<%@include file="./WEB-INF/includes/mainPane.jsp" %>
<table id="inner_content">
	<tr>
    	<td colspan="3" class="no_bottom_padding">
    	<div align="center">
    	<table id="page_title_table_row">
    	<tr>
    	<td>
        <div align="center" id="inner_content_title">
        <%
        if(verbose)
        {
        	System.out.println("Got to hasUser conditional");
        }
        ArrayList emailList = new ArrayList();
        ArrayList fnameList = new ArrayList();
        ArrayList mnameList = new ArrayList();
        ArrayList lnameList = new ArrayList();
        ArrayList passwordList = new ArrayList();
		if(!hasUser || !(myUser.getAttribute("role").equals("admin")))
		{
		%>
        Welcome to the Tigress Challenge Engine
        <%
		}
		else
		{
			ArrayList addedStudents = (ArrayList)request.getAttribute("studentsAdded");
			//Integer totalToAdd = new Integer(request.getParameter("totalAdd"));
			//out.print(totalToAdd);
			for(int x=0; x<addedStudents.size(); x++)
			{
				HashMap curMap = (HashMap) addedStudents.get(x);
				//out.print(x);
				String email = (String)curMap.get("email");
				String fname = (String)curMap.get("fname");
				String mname = (String)curMap.get("mname");
				String lname = (String)curMap.get("lname");
				String password = (String)curMap.get("password");
				//if(password.equals("Do not change for an autogenerated value."))
				//{
				//	password = UUID.randomUUID().toString();
				//}
				//myConnector.writeUser(email, email, fname, mname, lname, password, "student", (String)myUser.getAttribute("email"));
				emailList.add(email);
				fnameList.add(fname);
				mnameList.add(mname);
				lnameList.add(lname);
				passwordList.add(password);
				//out.print(password);
			}
		%>
        Welcome back, <% out.print(displayName); %>!
        <%
		}
		%>
        </div>
        <div align="center" id="inner_content_slogan">
        Obfuscation Made Easy</div>
        </td>
        </tr>
        </table>
        </div>
        </td>
    </tr>
	<tr>
    	<td width="25%">
        <table class="inner_content_table">
        <tr>
        <td>
        <table class="news_table">
        <tr class="title_general">
        <td colspan="3" align="center">
        Options
        </td>
    	</tr>
        <tr>
        <td>
        <table class="news_item_table" width="100%">
        <tr>
        <tr>
        <td colspan="2">
        <div align="center">
        <a href="addStudents.jsp">Back</a><br></br>
        </div>
        </td>
        </tr>
        <tr>
        <td width="100%">
        <div align="center">
        <b>CSV Upload</b>
        </div>
        </td>
        </tr>
        <form enctype="multipart/form-data" action="StudentCSVUpload" method="post">
        <tr>
        <td width="100%">
        <div align="center">
        <input type="file" name="csvFile"></input>
        </div>
        </td>
        </tr>
        <tr>
        <td width="100%">
        <div align="center">
        <input type="submit" value="Submit"></input>
        </div>
        </td>
        </tr>
        </form>
        </table>
        </td>
        </tr>
        </table>
        </td>
        </tr>
        </table>
        </td>
        <td width="50%">
        <table class="inner_content_table">
        <tr>
        <td>
        <table class="news_table">
        <tr class="title_general">
        <td colspan="3" align="center">
        Enter Information
        </td>
    	</tr>
        <tr>
        <td id="add_user_table">
        <%
        for(int x=0; x<emailList.size(); x++)
        {
        %>
        <table class="news_item_table" width="100%">
        <tr>
        <td width="33%">
        Student:
        </td>
        <td width="67%">
        <%=x %>
        </td>
        </tr>
        <tr>
        <td colspan="2">
        &nbsp;
        </td>
        </tr>
        <tr>
        <td width="33%">
        Email Address:
        </td>
        <td width="67%">
        <%=emailList.get(x) %>
        </td>
        </tr>
        <tr>
        <td width="33%">
        First Name:
        </td>
        <td width="67%">
        <%=fnameList.get(x) %>
        </td>
        </tr>
        <tr>
        <td width="33%">
        Middle Name:
        </td>
        <td width="67%">
        <%=mnameList.get(x) %>
        </td>
        </tr>
        <tr>
        <td width="33%">
        Last Name:
        </td>
        <td width="67%">
        <%=lnameList.get(x) %>
        </td>
        </tr>
        <tr>
        <td width="33%">
        Password:
        </td>
        <td width="67%">
        <%=passwordList.get(x) %>
        </td>
        </tr>
        </table>
        <%
        }
        %>
        </td>
        </tr>
        </table>
        </td>
        </tr>
        </table>
        </td>
        <td width="25%">
        <table class="inner_content_table">
        <tr>
        <td>
        <%
        if(verbose)
        {
        	System.out.println("Got to hasUser conditional");
        }
		if(!hasUser)
		{
		%>
        	<table class="news_table" width="100%">
            <tr class="title_general">
            <td>
        	<div align="center">Login<br /></div>
            </td>
            </tr>
            </table>
            <table class="news_item_table" width="100%">
            <tr>
            <td>
        	<%@include file="./WEB-INF/includes/loginWindow.jsp" %>
            </td>
            </tr>
            </table>
        <%
		}
		else
		{
		%>
        	<table class="news_table" width="100%">
            <tr class="title_general">
            <td>
        	<div align="center">Logout<br /></div>
            </td>
            </tr>
            </table>
        	<table class="news_item_table" width="100%">
            <tr>
            <td>
        	<div align="center">Hi there, <%=displayName %>! Your last visit was <%
				java.util.Date logonDate=(java.util.Date)myUser.getAttribute("previousVisit");
				out.print(dateFormat.format(logonDate));
				%>.  Your role is <%
				out.print(myUser.getAttribute("role") + ".");
				if(myUser.getAttribute("role").equals("student"))
				{
					out.print("  Your administrator is " + myUser.getAttribute("administrator"));
				}
				%>.<br />Not you?<br /></div>
            <%@include file="./WEB-INF/includes/logoutWindow.jsp" %>
            </td>
            </tr>
            </table>
        <%
		}
		if(verbose)
        {
        	System.out.println("Got past hasUser conditional");
        }
		%>
        </td>
        </tr>
        </table>
        </td>
    </tr>
</table>
<%@include file="./WEB-INF/includes/footer.jsp" %>
</body>

</html>